# Generated by Django 3.2 on 2022-05-25 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentrv', '0002_renter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renterPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentrv.renter')),
                ('rvItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentrv.rv')),
            ],
        ),
    ]
