# Generated by Django 3.2 on 2022-05-25 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentrv', '0003_rent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='renterPerson',
            new_name='renter',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='rvItem',
            new_name='rv',
        ),
    ]
